import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import RootLayoutClient from "./provider";

export const metadata: Metadata = {
  title: "Coding with buddy",
  description: "Generated by coder's love buddy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayoutClient>{children}</RootLayoutClient>;
}
